services:
  backend:
    container_name: chatbot_auth
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    container_name: chatbot_auth_postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5544:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
